
name: Main WorkFlow

on: [push, pull_request]

jobs:
    call-reusable-workflow:
        name: Call Reusable Workflow
        uses: nessadab/reusable-flows/.github/workflows/reusable-flow.yml@main
        with: 
         node-version: '18'
         npm-install-command: 'ci'
         run-playwright: true
         upload-artifact: true